Output demo.gif
Set Padding 10
#Set PlaybackSpeed 0.5 # Make output 2 times slower
Set WindowBar Colorful
Set TypingSpeed 100ms
Sleep 3s
Type "go run ./cmd/example/main.go foo bar biz bass buzz booboo baba"
Enter
Wait+Screen@15s  /booboo/
Sleep 1s
Set TypingSpeed 500ms
Down
Space
Down
Down
Space
Up
Space
Down
Space
Down
Down
Space
Down
Up
Up
Up
Up
Up
Up
Space
Down
Up
Down
Space
Up
Up
Space
Down
Space
Down
Down
Down
Down
Space
Sleep 3s
Enter
Sleep 6s
Ctrl+C